#!/bin/bash
set -euo pipefail

# Set Base Working Directory
basedir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

. "$basedir/lib/commit_summary.bash"

echo "--- Sending Hangouts Message"

WEBHOOK_URL="${BUILDKITE_PLUGIN_HANGOUTS_CHAT_WEBHOOK_URL?}"
CHAT_URL=${BUILDKITE_PLUGIN_HANGOUTS_CHAT_CHAT_ENDPOINT?}
MESSAGE=$(echo "${BUILDKITE_PLUGIN_HANGOUTS_CHAT_MESSAGE?}" | envsubst)

if [[ "${BUILDKITE_PLUGIN_HANGOUTS_CHAT_DEBUG:-false}" =~ (true|on|1) ]] ; then
  echo "--- :hammer: Enabling debug mode"
  set -x
fi

if [[ "${BUILDKITE_PLUGIN_HANGOUTS_CHAT_COMMIT_SUMMARY_ENABLED:-false}" =~ (true|on|1) ]] ; then
    # Generate Commit based message
    BK_FROM_COMMIT="${BUILDKITE_PLUGIN_HANGOUTS_CHAT_COMMIT_SUMMARY_FROM_COMMIT}"
    BK_TO_COMMIT="${BUILDKITE_PLUGIN_HANGOUTS_CHAT_COMMIT_SUMMARY_TO_COMMIT}"
    SUMMARY_LOG=$(commit_summary "$BK_FROM_COMMIT" "$BK_TO_COMMIT")

    MESSAGE="${MESSAGE} ${SUMMARY_LOG}"
fi

CURRENT_COMMIT=$(git rev-parse HEAD)
THREAD_KEY=${BUILDKITE_PLUGIN_HANGOUTS_CHAT_THREAD_KEY:=$CURRENT_COMMIT}

# # Post to Chat Service Endpoint
curl -v --location --request POST "${WEBHOOK_URL}" \
-H 'Content-Type: application/json' \
-d ' '"${MESSAGE}"' '
